name: Build and Lint

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
            go-version-file: 'go.mod'

      - name: Lint Go
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
